### ISSUE TITLE
Outputting radar contacts to the console?

### ISSUE THREAD

**Issue by ajlhowie** [Archaegeo/Archaegeo-Orbital-Hud#99]
Love using Arch Hud, keep up the good work.

I do quite a lot of AFK autopilot and would find it useful if new radar contacts could be outputted to the console so I don't miss any recent activity.

I imagine this would be fairly straightforward to do, and could be toggled via a parameter.

**Comment by Archaegeo** [comment]
Feel free to do so yourself, or look for a PvP HUD that might do so, or ask someone to do it on commission, but I dont see the worth of it other than flying down pipes looking for targets that you might miss without paying attention :).

If there is a valid purpose for folks, reply, otherwise this will probably be closed.

**Comment by ajlhowie** [comment]
Hi, thanks for the reply. I was wanting to use this to avoid pirates so I could alter my trajectory. 

Thanks for the advice it seems like i should be able to implement this myself.

Thanks.
